const STORE='pen_project_folio_v1';
const CARDS=[
  ["brief","Project Brief and Success Criteria","Show that you understand the Pen task, the approved sources and the difference between a finished object and a complete evidence package.","Verified task requirements, personal success criteria and links between function, quality, safe process and evidence.","What must your Pen and folio prove to be considered successful?",["My Pen must…","My evidence will prove…"],"A completed Pen connected to function, comfort, workmanship, safe process and evidence."],
  ["resource","Approved Resource and Kit Constraints","Show how the supplied Pen Making resource, current kit instructions and teacher directions control decisions without importing another kit’s details.","Annotated source notes, confirmed kit facts, questions for the teacher and a list of details that must not be guessed.","Which project decision depended most on the approved resource?",["The approved resource confirms…","I stopped and checked because…"],"An authority map linking the Pen Making resource, kit instructions, teacher demonstration and workshop SOP."],
  ["whs","WHS, WMS and Lathe Controls","Build a project-specific WMS that sequences the real Pen work and identifies hazards, controls and teacher hold points.","Task steps, hazard-event-consequence statements, hierarchy controls, SOP references, stop points and teacher approvals.","Which Pen hazard required the strongest practical control, and why?",["The hazard event was…","The higher-order control was…","Teacher approval was required before…"],"The Pen sequence beside the hierarchy of controls and supervised lathe hold points."],
  ["timber","Timber Selection and Grain Orientation","Explain how the approved blank was inspected and how the centre/grain reference preserved the visual relationship of the paired bodies.","Blank inspection, grain/defect observations, marked orientation line, paired-part identification and responsible material-use decision.","How did the grain reference affect a later Pen decision?",["I selected this blank because…","The centre/grain line helped me…"],"One timber blank becoming two identified Pen bodies whose grain relationship remains connected."],
  ["drilling","Brass Sleeves, Drilling and Swarf","Show the controlled preparation leading to two clean, teacher-approved holes and correctly prepared brass-sleeve surfaces.","Two identified sleeves, roughened outer surfaces, approved drilling setup, regular swarf-clearance records and hole-quality checkpoint.","Which preparation or drilling check prevented the greatest risk to later assembly?",["The sleeve surface was prepared to…","I cleared swarf because…","The teacher checkpoint confirmed…"],"A process diagram from paired blank and sleeves to inspected holes, with no unverified dimensions."],
  ["mandrel","Mandrel Setup and Pre-start Check","Prove that you identified the approved mandrel components, aligned the paired grain references and completed the supervised pre-start routine.","Mandrel with three collets and brass thumb screw, aligned centre/grain lines, isolation and pre-start checklist, teacher approval.","What evidence proves the setup was checked rather than merely assembled?",["I identified the approved components by…","Before starting, I verified…"],"A clean mandrel-preparation workflow with isolation, alignment and teacher approval gates."],
  ["turning","Controlled Turning and Profile Development","Explain how the Pen moved progressively from square to cylindrical form through observed, teacher-approved decisions.","Square, intermediate and cylindrical stages; surface observations; profile/alignment checks; stop decisions and teacher feedback.","Which observation most influenced your next turning decision?",["At this stage I observed…","I decided to stop/continue because…"],"A check–decide–act loop around three progressive Pen-body stages."],
  ["surface","Surface Diagnosis and Abrasive Sequence","Show how you diagnosed tool marks before using the approved progressive abrasive sequence and dust controls.","Close surface views, defect description, teacher-directed correction, each approved abrasive stage and readiness-for-finish check.","How did inspection stop sanding from simply hiding a turning fault?",["The surface defect appeared as…","Before the next abrasive stage, I checked…"],"Surface marks progressively refined through approved stages, with inspection gates between them."],
  ["finish","Approved Finish and Quality Checks","Explain how the actual product label, SDS, teacher demonstration and workshop procedure governed finishing.","Surface-readiness evidence, verified product-information notes, controlled application records, handling/curing checks and honest result observations.","What evidence proves the finish was suitable, not merely shiny?",["The approved product information required…","The finish result was consistent because…"],"A finish decision pathway from verified product information to inspected Pen surface."],
  ["assembly","Kit Components and Controlled Assembly","Show how the matched components were identified, staged, aligned and assembled without forcing or damaging the finished bodies.","Clean component inventory, protected surfaces, approved clip/button and nib-shroud stage, alignment checks and stop-for-resistance record.","Which assembly check protected the Pen from misalignment or damage?",["Before assembly, I confirmed…","When resistance changed, I…"],"A clean, principle-level assembly flow using alignment and stop checkpoints without invented kit geometry."],
  ["evidence","Photos, Flowchart and Problem Solving","Build a traceable production story through purposeful photographs, captions and an inputs–processes–outputs flowchart.","Safe stage photos, observation–decision–action–result captions, decision loops, inputs/processes/outputs and one genuine correction.","Which evidence item best proves that your process improved?",["This evidence shows…","The symptom was…","I confirmed the cause by…"],"A Pen production timeline with evidence checkpoints, a feedback loop and one documented improvement."],
  ["evaluation","PMI Evaluation and Skill Transfer","Judge the completed Pen honestly, connect the result to evidence and identify skills that transfer to future projects.","Final views, functional/comfort/alignment/surface/assembly checks, PMI, social/environmental trade-offs, limitations and next-step reflection.","How successfully does the completed Pen meet the approved brief, and what will you transfer?",["A plus supported by evidence is…","A minus and its cause are…","An interesting finding was…","Next project, I will transfer…"],"A final Pen surrounded by PMI evidence, impact trade-offs and transferable skills."]
]
.map((c,i)=>({id:i+1,key:c[0],title:c[1],purpose:c[2],evidence:c[3],prompt:c[4],starters:c[5],visual:c[6]}));
const $=id=>document.getElementById(id), enc=new TextEncoder(), dec=new TextDecoder();
const safe=s=>String(s||'pen-folio').trim().replace(/[^a-z0-9]+/gi,'-').replace(/^-+|-+$/g,'').toLowerCase()||'pen-folio';
const status=s=>$('folioStatus').textContent=s;
function cards(){ $('folioCards').innerHTML=CARDS.map(c=>`<article class="folio-card"><div class="folio-number">${c.id}<span>Card</span></div><div class="folio-body"><div class="folio-head"><div><p class="section-kicker">Evidence card ${c.id}</p><h2>${c.title}</h2></div><label class="folio-complete"><input type="checkbox" data-done="${c.key}"> Reviewed</label></div><div class="folio-guide" data-guide-slot="${c.key}"></div><div class="folio-meta"><article><h3>Why this matters</h3><p>${c.purpose}</p></article><article><h3>Evidence to collect</h3><p>${c.evidence}</p><h3>Visual idea</h3><p>${c.visual}</p></article></div><div class="folio-response-grid"><div class="folio-field"><label for="response-${c.key}">${c.prompt}</label><textarea id="response-${c.key}" data-response="${c.key}" placeholder="Write your response here…"></textarea></div><div class="folio-field"><label for="note-${c.key}">Evidence note or photo caption</label><textarea id="note-${c.key}" data-note="${c.key}" placeholder="What does your photo, sketch or check prove?"></textarea><details class="sentence-starters"><summary>Sentence starters</summary><ul>${c.starters.map(s=>`<li>${s}</li>`).join('')}</ul></details></div></div><div class="photo-panel"><h3>Add one useful photo</h3><p>Use your own build photo, sketch or check. It is included in the ZIP backup.</p><label class="photo-upload">Choose photo<input type="file" accept="image/*" data-photo="${c.key}"></label><img class="photo-preview" data-preview="${c.key}" alt="${c.title} evidence preview"></div></div></article>`).join(''); }
function session(){const r={},n={},d={},p={};CARDS.forEach(c=>{r[c.key]=$(`response-${c.key}`).value;n[c.key]=$(`note-${c.key}`).value;d[c.key]=document.querySelector(`[data-done="${c.key}"]`).checked;const i=document.querySelector(`[data-preview="${c.key}"]`);if(i.dataset.data)p[c.key]={name:i.dataset.name||`${c.key}.jpg`,data:i.dataset.data};});return{version:1,project:'Year 9 Timber Pen Project Folio',savedAt:new Date().toISOString(),student:{first:$('studentFirst').value,last:$('studentLast').value,className:$('studentClass').value,date:$('sessionDate').value},responses:r,notes:n,done:d,photos:p};}
function setPhoto(k,p){const i=document.querySelector(`[data-preview="${k}"]`);i.src=p.data;i.dataset.data=p.data;i.dataset.name=p.name||`${k}.jpg`;i.style.display='block';}
function apply(x){const s=x.student||{};$('studentFirst').value=s.first||'';$('studentLast').value=s.last||'';$('studentClass').value=s.className||'';$('sessionDate').value=s.date||'';CARDS.forEach(c=>{$(`response-${c.key}`).value=x.responses?.[c.key]||'';$(`note-${c.key}`).value=x.notes?.[c.key]||'';document.querySelector(`[data-done="${c.key}"]`).checked=!!x.done?.[c.key];if(x.photos?.[c.key])setPhoto(c.key,x.photos[c.key]);});save(false);status('Saved folio restored.');}
function progress(){const x=session(),done=CARDS.filter(c=>x.responses[c.key].trim()&&x.notes[c.key].trim()).length;$('progressCount').textContent=`${done} of ${CARDS.length} evidence cards complete`;$('progressBar').style.width=`${done/CARDS.length*100}%`;}
function save(show=true){localStorage.setItem(STORE,JSON.stringify(session()));progress();if(show)status(`Saved ${new Date().toLocaleTimeString()}.`);}
function compress(file){return new Promise((ok,bad)=>{const r=new FileReader();r.onerror=bad;r.onload=()=>{const im=new Image();im.onerror=bad;im.onload=()=>{const scale=Math.min(1,1400/Math.max(im.width,im.height)),can=document.createElement('canvas');can.width=Math.round(im.width*scale);can.height=Math.round(im.height*scale);can.getContext('2d').drawImage(im,0,0,can.width,can.height);ok({name:file.name.replace(/\.[^.]+$/,'.jpg'),data:can.toDataURL('image/jpeg',.82)});};im.src=r.result;};r.readAsDataURL(file);});}
function crc(b){let c=-1;for(let v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^(0xedb88320&-(c&1));}return(c^-1)>>>0;}function w16(a,o,v){a[o]=v&255;a[o+1]=v>>>8&255}function w32(a,o,v){a[o]=v&255;a[o+1]=v>>>8&255;a[o+2]=v>>>16&255;a[o+3]=v>>>24&255}function join(a){let n=a.reduce((x,y)=>x+y.length,0),r=new Uint8Array(n),o=0;a.forEach(x=>{r.set(x,o);o+=x.length});return r}
function zip(files){const l=[],c=[];let o=0;const now=new Date(),t=now.getHours()<<11|now.getMinutes()<<5|Math.floor(now.getSeconds()/2),d=now.getFullYear()-1980<<9|now.getMonth()+1<<5|now.getDate();files.forEach(f=>{const n=enc.encode(f.name),z=crc(f.bytes),h=new Uint8Array(30+n.length);w32(h,0,0x04034b50);w16(h,4,20);w16(h,10,t);w16(h,12,d);w32(h,14,z);w32(h,18,f.bytes.length);w32(h,22,f.bytes.length);w16(h,26,n.length);h.set(n,30);l.push(h,f.bytes);const q=new Uint8Array(46+n.length);w32(q,0,0x02014b50);w16(q,4,20);w16(q,6,20);w16(q,12,t);w16(q,14,d);w32(q,16,z);w32(q,20,f.bytes.length);w32(q,24,f.bytes.length);w16(q,28,n.length);w32(q,42,o);q.set(n,46);c.push(q);o+=h.length+f.bytes.length});const cd=join(c),end=new Uint8Array(22);w32(end,0,0x06054b50);w16(end,8,files.length);w16(end,10,files.length);w32(end,12,cd.length);w32(end,16,o);return join([...l,cd,end])}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}function b64(s){const raw=(s||'').split(',')[1]||'',bin=atob(raw);return Uint8Array.from(bin,x=>x.charCodeAt(0));}
function getZip(){const x=session(),f=[{name:'pen-folio-session.json',bytes:enc.encode(JSON.stringify(x,null,2))}];Object.entries(x.photos).forEach(([k,p])=>f.push({name:`photos/${k}-${p.name}`.replace(/[^\w./-]/g,'-'),bytes:b64(p.data)}));dl(new Blob([zip(f)],{type:'application/zip'}),`${safe(`${x.student.first}-${x.student.last}`)}-pen-folio-backup.zip`);status('ZIP backup downloaded with answers and photos.');}
const r16=(b,o)=>b[o]|b[o+1]<<8,r32=(b,o)=>(b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24)>>>0;
async function restore(f){try{if(f.name.toLowerCase().endsWith('.json'))return apply(JSON.parse(await f.text()));const b=new Uint8Array(await f.arrayBuffer());let o=0,json='';while(o<b.length&&r32(b,o)===0x04034b50){const size=r32(b,o+18),ns=r16(b,o+26),ex=r16(b,o+28),start=o+30+ns+ex,name=dec.decode(b.slice(o+30,o+30+ns));if(r16(b,o+8)!==0)throw Error();if(name==='pen-folio-session.json')json=dec.decode(b.slice(start,start+size));o=start+size}if(!json)throw Error();apply(JSON.parse(json));}catch{status('Could not read that backup. Use a ZIP or JSON downloaded from this folio.');}}
function init(){cards();$('sessionDate').value=new Date().toISOString().slice(0,10);try{const s=localStorage.getItem(STORE);if(s)apply(JSON.parse(s));}catch{localStorage.removeItem(STORE)}progress();document.addEventListener('input',e=>{if(e.target.matches('input,textarea'))save()});document.addEventListener('change',async e=>{if(e.target.matches('[data-photo]')){const f=e.target.files[0];if(f){setPhoto(e.target.dataset.photo,await compress(f));save()}e.target.value=''}else save()});$('downloadZip').onclick=getZip;$('downloadJson').onclick=()=>{const x=session();dl(new Blob([JSON.stringify(x,null,2)],{type:'application/json'}),`${safe(`${x.student.first}-${x.student.last}`)}-pen-folio-session.json`);status('JSON session downloaded.')};$('restoreSession').onclick=()=>$('restoreInput').click();$('restoreInput').onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=''};$('printFolio').onclick=()=>window.print();$('clearFolio').onclick=()=>{if(confirm('Clear all saved Pen folio work from this browser?')){localStorage.removeItem(STORE);location.reload()}}}document.addEventListener('DOMContentLoaded',init);

